//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poliedro.Billing.Infraestructure.Persistence.Mysql {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageProviderResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageProviderResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Poliedro.Billing.Infraestructure.Persistence.Mysql.MessageProviderResource", typeof(MessageProviderResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This field must be greather than 0.
        /// </summary>
        public static string ErrorValidatorFieldGreatherThanZero {
            get {
                return ResourceManager.GetString("ErrorValidatorFieldGreatherThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This field must be less than 12.
        /// </summary>
        public static string ErrorValidatorFieldLessThanTwelve {
            get {
                return ResourceManager.GetString("ErrorValidatorFieldLessThanTwelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This field cannot be empty.
        /// </summary>
        public static string ErrorValidatorFieldNotEmpty {
            get {
                return ResourceManager.GetString("ErrorValidatorFieldNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This field cannot be null.
        /// </summary>
        public static string ErrorValidatorFieldNotNull {
            get {
                return ResourceManager.GetString("ErrorValidatorFieldNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The resolution type must be valid (FE or POS).
        /// </summary>
        public static string ErrorValidatorResolutionTypeValid {
            get {
                return ResourceManager.GetString("ErrorValidatorResolutionTypeValid", resourceCulture);
            }
        }
    }
}
